In [49]:
import numpy as np
import time

In [ ]:
#python list 
size=1_000_000
py_list=list(range(size))
start=time.time()
sq_list=[i**2 for i in py_list]
end=time.time()
print(f"Time Taken : {end-start} sec" )
#numpy array
np_arr=np.array(py_list)
start=time.time()
arr_list=np_arr**2
end=time.time()
print(f"Time Taken : {end-start} sec" )


Time Taken : 0.1255934238433838 sec
Time Taken : 0.0021820068359375 sec


In [ ]:
#creating numpy Arrays
arr=np.array([1,2,3,4,5])
print(arr,type(arr))
#inbuilt type checker of numpy
print(arr.dtype)
#non-homogeneous elements
arr1=np.array([1,2,3,4,5,"prime"])
print(arr1,type(arr1))
#inbuilt type checker of numpy
print(arr1.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'>
int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'>
<U21


In [18]:
#use shape attribute

#1-dimensional array
arr2=np.array([1,2,3,4,5])
print(f"{arr2} \nDimension : {arr2.shape}")
#2-dimensional array
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"{arr3} \nDimension : {arr3.shape}")

[1 2 3 4 5] 
Dimension : (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
Dimension : (3, 3)


In [ ]:
#creat differnet types of arrays

arr1=np.array((2,3))
print(arr1,arr1.shape)

arr2=np.zeros((2,3))  #prefill with '0.' (floating data type)
print(arr2,arr2.shape)

arr3=np.zeros((2,3),dtype="int64")  #prefilled with '0' & set data type 
print(arr3,arr3.shape)

arr4=np.ones((4,3))  #prefilled with '1.' (floating) 
print(arr4,arr4.shape)

arr5=np.ones((9,) )  #1-D array with '1.' (floating)
print(arr5,arr5.shape)

arr6=np.full((2,3),100)  #filled with custom element
print(arr6,arr6.shape)

arr7=np.eye((4))  #identity matrix
print(arr7,arr7.shape)

arr8=np.arange(1,11)  #same as range function in python, arange(start,end,step)
print(arr8,arr8.shape)

arr9=np.arange(0,11,2)  #use steps to skip number
print(arr9,arr9.shape)

arr10=np.linspace(1,100,4)#evenly spaced array,linspace(start,end,no.of element)
print(arr10,arr10.shape)

arr11=np.linspace(1,100,11)#evenly spaced array
print(arr11,arr11.shape)


[2 3] (2,)
[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (4, 3)
[1. 1. 1. 1. 1. 1. 1. 1. 1.] (9,)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)
[  1.   10.9  20.8  30.7  40.6  50.5  60.4  70.3  80.2  90.1 100. ] (11,)


In [48]:
#imp attributes of array
arr1=np.array([0,1,2,3,4,5,6,7,8])
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)
print(arr1.ndim)

#type casting 
float_arr=arr1.astype(np.float64)
print(float_arr,float_arr.dtype)

float_arr.astype(np.int32)
print(float_arr,float_arr.dtype)
arr2=arr1.astype(str)
print(arr2,arr2.dtype)        # → array of strings
arr3=arr1.astype(bool)
print(arr3,arr3.dtype)       # 0 = False, nonzero = True

[0 1 2 3 4 5 6 7 8]
(9,)
9
int64
1
[0. 1. 2. 3. 4. 5. 6. 7. 8.] float64
[0. 1. 2. 3. 4. 5. 6. 7. 8.] float64
['0' '1' '2' '3' '4' '5' '6' '7' '8'] <U21
[False  True  True  True  True  True  True  True  True] bool


In [ ]:
#operations on array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr,arr.shape,arr.ndim)

arr1=arr.reshape((4,2))
print(arr1,arr1.shape,arr1.ndim)  #change the shape of matrix 

flattend=arr.flatten()  #2D arrray=>1D array
print(flattend,flattend.shape,flattend.ndim)  


[[1 2 3 4]
 [5 6 7 8]] (2, 4) 2
[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2) 2
[1 2 3 4 5 6 7 8] (8,) 1


In [62]:
# Normal Indexing (1D & 2D)

# 1-D array
print("1-D Array")
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[0])
print(arr[3])
print(arr[5])
print(arr[7])  #index value higher than the elements present then error gives out bound 

# 2-D array
print("2-D Array")
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1[1][2])
print(arr1[0][0])
print(arr1[1][4])
print(arr1[0][3])

#Fancy Indexing

arr2=np.array([1,2,3,4,5,6,7,7,8,8])
index=[0,3,4,2,7,9]
print(arr2[index])

# Boolean Indexing

arr3=arr2
print(arr[arr>3])
print(arr[arr%2==0])
print(arr[arr%2!=0])

1-D Array
1
4
6
8
2-D Array
8
1
10
4
[1 4 5 3 7 8]
[4 5 6 7 8]
[2 4 6 8]
[1 3 5 7]


In [67]:
#Slicing on array
arr= np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])
print(arr[1:5:2])

#In python, Slicing of list creates a new sub_list of the original arrays.
# slicing internally make view of the original array and showed to us, if we change on that sub_array it will reflect on original array also
# Copy Vs View
print("Python Slicing")

num=[1,2,3,4,5,6,7,8,9]
sub_list=num[1:4]
print(sub_list)
sub_list[2]=11
print(sub_list)
print(num)

print("Numpy Slicing")

arr=np.array(num)
sub_arr=arr[1:4]
print(sub_arr)
sub_arr[2]=12
print(sub_arr)
print(arr)

[2 3 4 5]
[2 3 4 5 6 7 8]
[1 2 3 4]
[1 2 3 4 5 6 7 8]
[1 3 5 7]
[2 4]
Python Slicing
[2, 3, 4]
[2, 3, 11]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
Numpy Slicing
[2 3 4]
[ 2  3 12]
[ 1  2  3 12  5  6  7  8  9]


In [76]:
#Multi-Dimensional array

# 2-D array
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(arr2d.sum())

#sum of columns
sum_of_columns=np.sum(arr2d,axis=0)
print(sum_of_columns)

#sum of rows
sum_of_rows=np.sum(arr2d,axis=1)
print(sum_of_rows)

#slicing in 2-D array
print(arr2d[0:2,1:2])
print(f"\n")
print(arr2d[0:2,1:3])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


[[2 3]
 [5 6]]


In [84]:
#3-D Array
arr3d=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3d,arr3d.shape)

#indexing
print(arr3d[0,1,1])
print(arr3d[1,1,1])

#slicing
print(arr3d[: ,0, :])
print(arr3d[: ,:, 0])


arr3d[: ,0, :]=99
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
10
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [90]:
# Vectorization
arr=np.array([1,2,3,4,5,6,7,8])
arr1=arr

print(arr**2)
print(arr + 20)
print(arr+arr1) 

#broadcasting
print(arr + 5)
arr2=np.array([1,2,3,4,5,6,7,8])
arr3=np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
print(arr2+arr3)
print(arr2.shape)
print(arr3.shape)

[ 1  4  9 16 25 36 49 64]
[21 22 23 24 25 26 27 28]
[ 2  4  6  8 10 12 14 16]
[ 6  7  8  9 10 11 12 13]
[[ 2  4  6  8 10 12 14 16]
 [ 2  4  6  8 10 12 14 16]]
(8,)
(2, 8)


In [95]:
#normalization
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
print(mean)
std_dev=np.std(arr)
print(std_dev)
normalization_arr=(arr-mean)/std_dev
print(normalization_arr)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [ ]:
#Aggreagation
arr=np.array([1,2,3,4,5,6,7,8,9])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.median(arr))
print(np.argmin(arr))
print(np.argmax(arr))


45
362880
1
9
5.0
2.581988897471611
6.666666666666667
5.0
0
8


In [100]:
#power
arr=np.array([1,2,3,4,5,6,7,8,9])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,4))

[ 1  4  9 16 25 36 49 64 81]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[   1   16   81  256  625 1296 2401 4096 6561]


In [101]:
# Log & Exponential
arr=np.array([1,2,3,4,5,6,7,8,9])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [102]:
#Rounding
arr=np.array([1.11,2.22,3.33,4.98,5.65,6.34,7.87,8.43,9.55])

print(np.round(arr))
print(np.ceil(arr))
print(np.floor(arr))
print(np.trunc(arr))

[ 1.  2.  3.  5.  6.  6.  8.  8. 10.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [103]:
#Extras
arr=np.array([1,-2,3,-4,-5,6,7,-8,9])

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

[-8 -5 -4 -2  1  3  6  7  9]
[-8 -5 -4 -2  1  3  6  7  9]
[1 2 3 4 5 6 7 8 9]
